general {
    hide_cursor = true
}

background {
    monitor =
    path = screenshot
    blur_size = 5
    blur_passes = 3
    noise = 0
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 2

    dots_size = 0.25
    dots_spacing = 0.15
    dots_center = true

    outer_color = rgba(f38ba8ff) rgba(ff005dff) 45deg
    inner_color = rgba(040405ff)

    font_color = rgba(f38ba8ff)

    fade_on_empty = true
    fade_timeout = 3000
    placeholder_text = <i>Password...</i>
    fail_text = <i>FUCK YOU</i>

    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(ffffffff)
    font_size = 64
    font_family = CayskadiaCove Nerd Font

    position = 0, 200
    halign = center
    valign = center
}
