wallpaper {
    monitor = DP-2
    path = ~/Documents/render pictures/CrystalFract.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Documents/render pictures/CrystalFract.png
    fit_mode = cover
}

splash = false
